---
title: "Assigment - Data Problems vs Data Solutions"
author: "Sjoerd Hamaker"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_notebook:
    toc: yes
    toc_depth: 2
---

## Big Data and analytics in action: Case study examples


<iframe width="560" height="315" src="https://www.youtube.com/embed/ypbSMS8XrAE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## What was the business problem?

The customer wanted to know more about the effectiveness of placement of their content within webstore fronts. The goal was to find out what customer behavior looked like, what the preferences were, and to distinguish viewing patterns of visitors to optimize advertising.

## How was it translated into a data mining problem?

A dataset about viewing patterns of visitors could be used to track "pathing" - to follow customers as they go from channel to channel.
I assumed, before watching, the data mining could look like the following:
-The data mining method is unsupervised: the business is attempting to find patterns in customer behavior. The data is not labeled and the outcome is unknown, there is no target (Provost, 2013).
-An interesting algorithm to use could be clustering: in which way could customers be grouped, given their pathing on the website, linked to their profile. By creating these clusters, advertisements could be better placed and/or targeted towards individual customers (Provost, 2013).

The video tells a neural network is created, which shows the connection points of the highest probability between several channels. For me, this could both be clustering or similarity matching, in which one attempts to identify similar individuals based on data known about them. 

## What is the realized business value?

Advertisements could be targeted better towards certain people visiting certain channels. In that way, advertising is more relevant to the individual customer, and this could lead to more clicks on those advertisements, which could lead to more sales.

## Sources
Provost, F., & Fawcett, T. (2013). Data Science for Business. O’Reilly.